version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      sigstore:
        patterns:
          - "github.com/sigstore/*"
      go-containerregistry:
        patterns:
          - "github.com/google/go-containerregistry"
      go-openapi:
        patterns:
          - "github.com/go-openapi/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
