version: 2

project_name: nri-supply-chain

builds:
  - main: ./cmd/nri-supply-chain/
    binary: nri-supply-chain
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - binary

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --bundle=${signature}
      - --yes
      - ${artifact}
    artifacts: checksum

sboms:
  - artifacts: binary

changelog:
  sort: asc
