{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nri-supply-chain.fullname" . }}-grafana-dashboard
  namespace: {{ include "nri-supply-chain.namespace" . }}
  labels:
    {{- include "nri-supply-chain.labels" . | nindent 4 }}
    grafana_dashboard: "1"
    {{- with .Values.monitoring.grafana.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.grafana.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  nri-supply-chain.json: |-
    {{- .Files.Get "files/dashboard.json" | nindent 4 }}
{{- end }}
