{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nri-supply-chain.fullname" . }}
  namespace: {{ include "nri-supply-chain.namespace" . }}
  labels:
    {{- include "nri-supply-chain.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nri-supply-chain.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
