{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nri-supply-chain.fullname" . }}
  namespace: {{ include "nri-supply-chain.namespace" . }}
  labels:
    {{- include "nri-supply-chain.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "nri-supply-chain.selectorLabels" . | nindent 4 }}
{{- end }}
